backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: volumes
    label: Volumes
    label_singular: 'Volume'
    folder: "content/volumes"
    path: '{{slug}}/index'
    media_folder: ''
    public_folder: ''
    create: true
    fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Color", name: "color", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}